name: 'Setup Auto'
description: 'GitHub Action to install Auto release tool'
branding:
  icon: at-sign
  color: yellow
inputs:
  version:
    description: 'Version of Auto to install (latest by default)'
    default: 'latest'
    required: false
runs:
  using: composite
  steps:
    - name: Install Auto binary
      shell: bash
      run: |
        platform='linux'
        [ '${{ runner.os }}' == 'macOS' ] && platform='macos'
        [ '${{ runner.os }}' == 'Windows' ] && platform='win.exe'
        name="auto-${platform}"
        tmp="${{ runner.temp }}"

        echo "Fetch: ${{ inputs.version }}"
        echo "curl -sL https://api.github.com/repos/intuit/auto/releases/${{ inputs.version }}"

        link=$(curl -sL "https://api.github.com/repos/intuit/auto/releases/${{ inputs.version }}" | jq -r ".assets | .[] | select(.name == \"$name.gz\") | .browser_download_url")
        echo "Download: $link"
        curl -sL $link -H "Accept: application/octet-stream" -o "$tmp/$name.gz"

        echo "Unzip: $tmp/$name.gz"
        gunzip "$tmp/$name.gz"
        chmod +x "$tmp/$name"

        echo "Move: $tmp/$name => $HOME/bin/auto"
        mkdir "$HOME/bin"
        mv "$tmp/$name" "$HOME/bin/auto"
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Check Auto installation
      shell: bash
      run: |
        auto --help
