name: 'Setup Auto'
description: 'GitHub Action to install Auto release tool'
branding:
  icon: at-sign
  color: yellow
inputs:
  version:
    description: 'Version of Auto to install (latest by default)'
    default: 'latest'
    required: false
  git-user:
    description: 'Git user name to set for Auto'
    required: false
    default: 'github-actions[bot]'
  git-email:
    description: 'Git email to set for Auto'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.pharos.com'
runs:
  using: composite
  steps:
    - name: Set up GitHub credentials for Auto
      shell: bash
      run: |
        # git config user
        git config user.name "${{ inputs.git-user }}"
        git config user.email "${{ inputs.git-email }}"

    - name: Install Auto binary
      shell: bash
      run: |
        # install auto binary
        platform='linux'
        [ '${{ runner.os }}' == 'macOS' ] && platform='macos'
        [ '${{ runner.os }}' == 'Windows' ] && platform='win.exe'
        name="auto-${platform}"
        tmp="${{ runner.temp }}"

        link=$(curl -sL "https://api.github.com/repos/intuit/auto/releases/${{ inputs.version }}" | jq -r ".assets | .[] | select(.name == \"$name.gz\") | .browser_download_url")
        curl -sL $link -H "Accept: application/octet-stream" -o "$tmp/$name.gz"

        gunzip "$tmp/$name.gz"
        chmod +x "$tmp/$name"

        mkdir "$HOME/bin"
        mv "$tmp/$name" "$HOME/bin/auto"
        echo "$HOME/bin" >> $GITHUB_PATH

        link='https://raw.github.pharos.com/pharos/.github/main/auto-default.json'
        curl -sL $link -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -o "$HOME/bin/.autorc.json"
        cat "$HOME/bin/.autorc.json"
